repos:
-   repo: local
    hooks:
    -   id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
        args: [
            "--cov=.",
            "--cov-report=term-missing",
            "test_MediaCollection.py"
        ] 